name: IDK
favicon: null
layout_spectrum: 0.7158783262129873
typography_spectrum: 0.178540478926152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.05376211879774928
  lightness: 0.2826772367116064
  saturation: 0.5380836906842887
  rhythmicContrast: 0.4921068730764091
purpose: []
